services:
  api-gateway:
    build: 
      context: ./ms-api-gateway
    ports:
      - 8080:80
  ms-db:
    build:
      context: ./ms-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db-data: