services:
  ms-api-gateway:
    build:
      context: ./ms-api-gateway
    restart: always
    ports:
      - 8080:80
    depends_on:
      - ms-delete
      - ms-get
      - ms-post
      - ms-put
    volumes:
      - ./ms-api-gateway/log/nginx:/var/log/nginx
  ms-db:
    build:
      context: ./ms-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  ms-delete:
    build:
      context: ./ms-delete
    restart: always
    depends_on:
      ms-db:
        condition: service_healthy
    environment:
      spring.datasource.url: ${DB_POSTGRES_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.jpa.hibernate.ddl-auto: update
  ms-get:
    build:
      context: ./ms-get
    restart: always
    depends_on:
      ms-db:
        condition: service_healthy
    environment:
      spring.datasource.url: ${DB_POSTGRES_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.jpa.hibernate.ddl-auto: update
  ms-post:
    build:
      context: ./ms-post
    restart: always
    depends_on:
      ms-db:
        condition: service_healthy
    environment:
      spring.datasource.url: ${DB_POSTGRES_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.jpa.hibernate.ddl-auto: update
  ms-put:
    build:
      context: ./ms-put
    restart: always
    depends_on:
      ms-db:
        condition: service_healthy
    environment:
      spring.datasource.url: ${DB_POSTGRES_URL}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.jpa.hibernate.ddl-auto: update
volumes:
  db-data: